"""Add more fields to document model

Revision ID: 90656a329a63
Revises: 9fefd7f1cdac
Create Date: 2026-08-15 20:25:29.877167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90656a329a63'
down_revision: Union[str, Sequence[str], None] = '9fefd7f1cdac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('stored_filename', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('storage_path', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('document_type', sa.String(length=20), nullable=True))
    op.add_column('documents', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.add_column('documents', sa.Column('file_size', sa.BigInteger(), nullable=True))
    op.create_unique_constraint('uq_documents_user_content_hash', 'documents', ['user_id', 'content_hash'])
    op.create_unique_constraint('uq_documents_user_name', 'documents', ['user_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_documents_user_name', 'documents', type_='unique')
    op.drop_constraint('uq_documents_user_content_hash', 'documents', type_='unique')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'content_hash')
    op.drop_column('documents', 'document_type')
    op.drop_column('documents', 'storage_path')
    op.drop_column('documents', 'stored_filename')
    # ### end Alembic commands ###
