"""add document fields

Revision ID: b29911ef6794
Revises: 90656a329a63
Create Date: 2026-08-16 18:39:43.253255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b29911ef6794'
down_revision: Union[str, Sequence[str], None] = '90656a329a63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('page_start', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('page_end', sa.Integer(), nullable=True))
    op.create_unique_constraint('uq_document_chunks_document_index', 'document_chunks', ['document_id', 'chunk_index'])
    op.add_column('documents', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'processed_at')
    op.drop_column('documents', 'error_message')
    op.drop_constraint('uq_document_chunks_document_index', 'document_chunks', type_='unique')
    op.drop_column('document_chunks', 'page_end')
    op.drop_column('document_chunks', 'page_start')
    # ### end Alembic commands ###
